AspNetEmailExample/Models/MailRecipient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace AspNetEmailExample.Models
{
    public partial class MailRecipient
    {
        public MailRecipient()
        {
            this.SentMails = new HashSet<SentMail>();
        }
        
        [Key]
        [Required]
        public int MailRecipientId { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string FirstName { get; set; }

        public string Email { get; set; }

        public string Company { get; set; }

        public string FullName
        {
            get
            {
                return string.Format("{0} {1}", this.FirstName, this.LastName);
            }
        }


        public DateTime? getLastEmailDate()
        {
            var top = (from m in this.SentMails
                       orderby m.SentDate descending
                       select m).Take(1);
            if (top.Count() > 0)
            {
                return top.ElementAt(0).SentDate;
            }
            else
            {
                return null;
            }
        }
    
        public virtual ICollection<SentMail> SentMails { get; set; }
    }
}

AspNetEmailExample/Models/MailRecipientsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AspNetEmailExample.Models
{
    public class MailRecipientsViewModel
    {
        public List<SelectRecipientEditorViewModel> MailRecipients { get; set; }
        public MailRecipientsViewModel()
        {
            this.MailRecipients = new List<SelectRecipientEditorViewModel>();
        }


        public IEnumerable<int> getSelectedRecipientIds()
        {
            return (from r in this.MailRecipients 
                    where r.Selected 
                    select r.MailRecipientId).ToList();
        }
    }
}

AspNetEmailExample/Controllers/MailRecipientsController.cs
using AspNetEmailExample.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Threading;

namespace AspNetEmailExample.Controllers
{
    public class MailRecipientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public async Task<ActionResult> Index()
        {
            var model = new MailRecipientsViewModel();

            // Get a list of all the recipients:
            var recipients = await db.MailRecipients.ToListAsync();
            foreach(var item in recipients)
            {
                // Put the relevant data into the ViewModel:
                var newRecipient = new SelectRecipientEditorViewModel()
                {
                    MailRecipientId = item.MailRecipientId,
                    FullName = item.FullName,
                    Company = item.Company,
                    Email = item.Email,
                    LastMailedDate = item.getLastEmailDate().HasValue ? item.getLastEmailDate().Value.ToShortDateString() : "",
                    Selected = true
                };

                // Add to the list contained by the "wrapper" ViewModel:
                model.MailRecipients.Add(newRecipient);
            }
            // Pass to the view and return:
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MailRecipient mailrecipient = await db.MailRecipients.FindAsync(id);
            if (mailrecipient == null)
            {
                return HttpNotFound();
            }
            return View(mailrecipient);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="LastName,FirstName,Email,Company")] MailRecipient mailrecipient)
        {
            if (ModelState.IsValid)
            {
                db.MailRecipients.Add(mailrecipient);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(mailrecipient);
        }


        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MailRecipient mailrecipient = await db.MailRecipients.FindAsync(id);
            if (mailrecipient == null)
            {
                return HttpNotFound();
            }
            return View(mailrecipient);
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include=
            "MailRecipientId,LastName,FirstName,Email,Company")] 
            MailRecipient mailrecipient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mailrecipient).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(mailrecipient);
        }


        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MailRecipient mailrecipient = await db.MailRecipients.FindAsync(id);
            if (mailrecipient == null)
            {
                return HttpNotFound();
            }
            return View(mailrecipient);
        }


        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            MailRecipient mailrecipient = await db.MailRecipients.FindAsync(id);
            db.MailRecipients.Remove(mailrecipient);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [HttpPost]
        [Authorize]
        public ActionResult SendMail(MailRecipientsViewModel recipients)
        {
            // Retrieve the ids of the recipients selected:
            var selectedIds = recipients.getSelectedRecipientIds();

            // Grab the recipient records:
            var selectedMailRecipients = this.LoadRecipientsFromIds(selectedIds);

            // Build the message container for each:
            var messageContainers = this.createRecipientMailMessages(selectedMailRecipients);

            // Send the mail:
            var sender = new MailSender();
            var sent = sender.SendMail(messageContainers);

            // Save a record of each mail sent:
            this.SaveSentMail(sent);

            // Reload the index form:
            return RedirectToAction("Index");
        }


        IEnumerable<MailRecipient> LoadRecipientsFromIds(IEnumerable<int> selectedIds)
        {
            var selectedMailRecipients = from r in db.MailRecipients
                                         where selectedIds.Contains(r.MailRecipientId)
                                         select r;
            return selectedMailRecipients;
        }


        IEnumerable<Message> createRecipientMailMessages(IEnumerable<MailRecipient> selectedMailRecipients)
        {
            var messageContainers = new List<Message>();
            var currentUser = db.Users.Find(User.Identity.GetUserId());
            foreach (var recipient in selectedMailRecipients)
            {
                var msg = new Message()
                {
                    Recipient = recipient,
                    User = currentUser,
                    Subject = string.Format("Welcome, {0}", recipient.FullName),
                    MessageBody = this.getMessageText(recipient, currentUser)
                };
                messageContainers.Add(msg);
            }
            return messageContainers;
        }


        void SaveSentMail(IEnumerable<SentMail> sentMessages)
        {
            foreach (var sent in sentMessages)
            {
                db.SentMails.Add(sent);
                db.SaveChanges();
            }
        }


        string getMessageText(MailRecipient recipient, ApplicationUser user)
        {
            return ""
            + string.Format("Dear {0}, ", recipient.FullName) + Environment.NewLine
            + "Thank you for your interest in our latest product. Please feel free to contact me for more information!"
            + Environment.NewLine
            + Environment.NewLine
            + "Sincerely, "
            + Environment.NewLine
            + string.Format("{0} {1}", user.FirstName, user.LastName);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AspNetEmailExample/Views/MailRecipients/Create.cshtml
@model AspNetEmailExample.Models.MailRecipient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MailRecipient</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AspNetEmailExample/Views/MailRecipients/Delete.cshtml
@model AspNetEmailExample.Models.MailRecipient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MailRecipient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AspNetEmailExample/Views/MailRecipients/Details.cshtml
@model AspNetEmailExample.Models.MailRecipient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MailRecipient</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MailRecipientId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AspNetEmailExample/Views/MailRecipients/Edit.cshtml
@model AspNetEmailExample.Models.MailRecipient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MailRecipient</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MailRecipientId)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company)
                @Html.ValidationMessageFor(model => model.Company)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AspNetEmailExample/Views/MailRecipients/Index.cshtml
@model AspNetEmailExample.Models.MailRecipientsViewModel

@{
    ViewBag.Title = "Email";
}

<h2>Send Email to Selected Recipients</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("SendMail", "MailRecipients", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
{
    // Add a "Check All" checkbox above the table:
    <div>
        <input type="checkbox" id="checkall" /><span>Check All</span>
    </div>
    
    // Wrap the table in a named <div> so we can refer to it from JQuery:
    <div id="checkboxes">

        <table class="table">
            <tr>
                <th>
                    @*This column will contain our checkboxes:*@
                    Select
                </th>
                <th>
                    @*This column will now hold a concatenation of the first/last names:*@
                    Name
                </th>
                <th>
                    Company
                </th>
                <th>
                    Email
                </th>
                <th>
                    Last Sent
                </th>
                <th></th>
            </tr>
            @* Our Table rows will be populated in the EditorTemplate: *@
            @Html.EditorFor(model => model.MailRecipients)
        </table>
    </div>
    <hr />
    <br />
    
    //Add a submit button to the bottom of the form:
    <input type="submit" name="operation" id="email" value="Email Selected" />
}

<div id="divProcessing">
    <p>Processing, please wait . . . <img src="../../Content/ajax-loader.gif"></p>
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

        <script type="text/javascript">

            function toggleChecked(status) {
                $("#checkboxes input").each(function () {
                    $(this).prop("checked", status);
                });
            }

            $(document).ready(function () {

                // Grab a reference to the checkall checkbox:
                var checkAllBox = $("#checkall");
                var divProcessing = $("#divProcessing");

                // Hide the animated Gif when page loads:
                divProcessing.hide();
                checkAllBox.prop('checked', true);


                // Attach a handler for the checkAllBox click event:
                checkAllBox.click(function () {
                    var status = checkAllBox.prop('checked');
                    toggleChecked(status);
                });

                $('#email').click(function () {
                    // Required hack to get animated gif to run in IE:
                    setTimeout(function () {
                        divProcessing.show();
                    }, 100);
                    $('myform').submit();
                });
            });
        </script>
    }